services:
  firebase:
    container_name: firebase-emulator
    build:
      context: ./firebase
    ports:
      - 8080:8080 # **FIRESTORE_PORT**
      - 5005:5005 # **FIRESTORE_WS_PORT**
      - 4000:4000 # **UI_PORT**
      - 8085:8085 # **PUBSUB_PORT**
      - 5001:5001 # **FUNCTIONS_PORT**
      - 9099:9099 # **AUTH_PORT**
      - 9199:9199 # **STORAGE**